"use client"
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import React from "react"
export default function Profile() {
      const router = useRouter();

      return (
            <>
                  <div >
                        <h1 className="w-full  justify-center items-center text-center bg-gradient-to-r from-[rgb(168,85,247)] to-[rgb(59,130,246)] text-white" >
                              <div className="w-full h-fit mt-2 pt-3 " >
                                    <div className="text-2xl pt-10 mt-2 " > SOLUTIONS </div>
                                    < div className="text-4xl font-bold font-mono mt-2" > Terms & Conditions </ div>
                                    < div className="text-2xl mt-2" > Please read all terms and conditions very careful </ div>
                                    < div className="text-lg pb-10 mt-2" > Last Updated:April 20, 2026 </ div>
                              </div>
                        </h1>
                        < div className="grid sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-2 p-10 gap-15 bg-gray-300 text-black text-justify w-full h-full" >
                              <p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 1. Acceptance of Terms

                                    By accessing or using the Multi-Disease Detection System(“Service”), you agree to comply with and be bound by these Terms and Conditions.If you do not agree with any part of these terms, you must not use the Service.</p>

                              < p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 2. Purpose of the Service

                                    The Multi - Disease Detection System is designed to analyze user - provided health data and provide predicted results related to possible diseases using machine learning or artificial intelligence models.

                                    ⚠️ The Service is intended for informational and educational purposes only and does not replace professional medical advice, diagnosis, or treatment. </ p>

                              < p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 3. User Responsibilities

                                    Users agree to:

                                    Provide accurate and truthful health information.
                                    Use the system only for lawful purposes.
                                    Not misuse or attempt to damage the system.
                                    Consult a qualified medical professional before making any medical decisions based on system predictions.</ p  >

                              < p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 4. Medical Disclaimer

                                    The results generated by the system:

                                    Are predictions based on available data and algorithms.
                                    May not always be accurate.
                                    Should not be considered a medical diagnosis.

                                    Users should always seek advice from a licensed healthcare professional for medical concerns.</ p>

                              < p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 5. Data Privacy

                                    The system may collect and process user data such as:

                                    Health parameters
                                    Uploaded reports or images
                                    Basic user information

                                    All data will be handled in accordance with applicable data protection and privacy laws.The system will take reasonable measures to protect user data.</ p>

                              < p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 6. Limitation of Liability

                                    The developers or owners of the Multi - Disease Detection System are not responsible for:

                                    Any incorrect predictions.
                                    Medical decisions taken based on the system’s results.
                                    Any loss, damage, or injury resulting from reliance on the Service.

                                    Use of the system is at the user's own risk.</ p >

                              < p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 7. System Availability

                                    We do not guarantee that the system will be:

                                    Available at all times
                                    Free from errors
                                    Completely secure

                                    The service may be updated, modified, or discontinued at any time without prior notice.</ p >

                              < p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 8. Intellectual Property

                                    All content, algorithms, design, and software related to the Multi - Disease Detection System are the intellectual property of the developers and may not be copied, modified, or redistributed without permission.</ p   >

                              <p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 9. Changes to Terms

                                    We reserve the right to modify or update these Terms and Conditions at any time.Continued use of the system after changes indicates acceptance of the updated terms.</p>

                              <p className="max-w-4xl pt-6 pb-2 pr-4 pl-4 mx-auto rounded-2xl shadow-lg bg-white  hover:bg-purple-400 hover:text-white" > 10. Contact Information

                                    If you have any questions regarding these Terms and Conditions, please contact:

                                    📧 Email: support @example.com

                                    📍 Address: Your Organization / Institution </p>
                        </div>
                  </div>

            </ >



      )
};